name: babble
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  #Services Packages
  #firebase_crashlytics: ^3.4.5
  #firebase_core: ^2.23.0
  #firebase_core: ^2.15.1
  #firebase_app_check: ^0.1.5+2
  #firebase_auth: ^4.7.2
  #flutter_firebase_recaptcha: ^1.0.2
  #google_sign_in: ^6.1.4



  #Architecture Packages
  get_it: ^9.2.0
  injectable: ^2.7.1
  go_router: ^17.1.0
  dio: ^5.9.1                           #для REST/CURL запросов
  retrofit: ^4.1.0                        #для упрощенной разработки запросов на основе dio/http
  supabase_flutter: ^2.12.0
  flutter_dotenv: ^6.0.0                   #для управления переменными окружения

#  http_parser: ^4.0.2                     #для загрузки файлов на сервер
  #web_socket_channel: ^2.4.0             #для чатов на websocket-ах
  #socket_io_client: ^2.0.3+1             #для чатов на websocket-ах
  json_annotation: ^4.8.1                 #для генерации моделей и dto
  freezed_annotation: ^3.1.0              #для генерации моделей и dto
  #auto_mappr_annotation: ^2.1.0           #для сопоставления моделей к dto
  flutter_bloc: ^9.1.1
  talker_flutter: ^5.1.13                          #для логирования


  #Features Packages
  connection_notifier: ^2.0.1             #для отслеживания connect-соединения
  shared_preferences: ^2.5.4
  #flutter_secure_storage: ^9.2.2
  image_picker: ^1.2.1

  #Compute Packages
  #phone_numbers_parser: ^8.3.0            #для валидации номера телефона любого региона
  uuid: ^4.5.2



  #UI Packages
  flutter_svg: ^2.2.3                     #для векторных изображений
  cached_network_image: ^3.4.1            #для загрузки фото по url с кэшированием внутри приложения
  #pinput: ^3.0.0                          #для ввода Pin-кода
  #shimmer: ^3.0.0                         #для шиммер-анимации загрузки

  #blur: ^3.1.0                            #для blur эффекта
  #flutter_switch: ^0.3.2                 #для switch-виджета (переключатель)

  #flutter_blurhash: ^0.8.2               #для blur оптимизированного blur-эффекта на основе предзагруженного изображения
  #flutter_slidable: ^3.0.1               #для слайдинга-элементов, например для сдвига кнопок чатов, и выбора контекстных действий вроде mute chat/delete chat/archive chat etc
  #cupertino_icons: ^1.0.2                #для ios иконок
  #step_progress_indicator: ^1.0.2        #для разных индикаторов загрузки
  #country_icons: ^2.0.2                  #для отображения флагов стран
  #dots_indicator: ^2.1.1                 #для индикации текущей страницы (отображение точками)
  #share_plus: ^7.1.0                     #для кнопки поделится
  #gradient_borders: ^1.0.0                #для градиентных барьеров
#  wolt_modal_sheet: ^0.5.0

dev_dependencies:
  freezed: ^3.2.5
  build_runner: ^2.11.0                    #для кодогенерации      #для кодогенерации навигации
  json_serializable: ^6.12.0               #для кодогенерации моделей и dto
  retrofit_generator: ^10.2.3              #для кодогенерации REST/CURL запросов
  flutter_lints: ^6.0.0                   #линтер
  injectable_generator: ^2.12.0            #для кодогенерации dependency injection
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - .env
  #   - assets/svg/
  #   - assets/png/
